### ISSUE TITLE
We should be able to reopen a step

### ISSUE THREAD

**Issue by kernixski** [kullervo16/checklist#32] opened 2016-07-28 08:59 UTC
The user can do mistakes.  If the user select the wrong answer for a question, there is no way to change it.  A closed step should be reopenable if the following step is not closed.

**Comment by kullervo16** [comment] 2016-07-30 10:43
this is a duplicate of #17, with minor difference that you ask to look at the following step, which makes sense... general "reopen step" is not the idea... you can re-execute the action in case of a problem and revalidate in case of a problem... once you indicate that everyting is ok, it should remain unchanged..

**Comment by kullervo16** [comment] 2016-10-25 18:37
One side-effect is of course that this way, you can "roll back" your complete checklist... each time you reopen a step, the reopen button appears 1 step higher... well, not that bad actually... that way it is clear since you have modified at that level, you should repass what follows.

The reopen will clear all errors, choices and answers...

**Comment by kullervo16** [comment] 2016-10-25 18:39
additional case : when you change your answer, this will need to unset the ones based on this decision (why can't people just not make mistakes... so much easier to program :-) )

**Closed** 2016-10-25 18:52 UTC
